services:
  - type: web
    name: memematch-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true # Render сам сгенерирует надежный секретный ключ
      - key: ADMIN_ID
        value: "1" # ID твоего админа-чайника